### ISSUE TITLE
decode: Add support for Request enum variants without params

### ISSUE THREAD

**Issue by formiat** [oasisprotocol/oasis-cbor#28]
Duplicated also here: https://github.com/oasisprotocol/oasis-sdk/issues/995

It will be more convenient to have opportunity to use `Request` enums with no params. Example:

```rust
#[derive(Clone, Debug, cbor::Encode, cbor::Decode)]
pub enum Request {
    #[cbor(rename = "instantiate")]
    Instantiate,

    <...>
}
```

This example doesn't work, because we receive error when we try to instantiate. None of these variants work:
`oasis contracts instantiate <code_id> 'instantiate'`
`oasis contracts instantiate <code_id> '{instantiate}'`
`oasis contracts instantiate <code_id> '{instantiate: {}}'`

We receive error: `Execution failed with error: module: contracts code: 12 message: execution failed: unreachable executed`

**Comment by kostko** [comment]
This should already be supported (it uses just a CBOR text string, e.g. `"instantiate"` in this case unless you pass `#[cbor(as_struct)]` to the variant in which case it uses a map).

It could rather be an issue with the CLI that does something weird when parsing the arguments. Will close this issue and let's discuss in oasisprotocol/oasis-sdk#995.
