### ISSUE TITLE
u64 decoding fails if value below 4294967296

### ISSUE THREAD

**Issue by CedarMist** [oasisprotocol/oasis-cbor#36]
I've added a testcase which demonstrates that parsing u64 fails at the u32 & u64 boundary.

https://github.com/oasisprotocol/oasis-cbor/commit/4b3b721d9238b1d53a43cbffb96c9f7391cf07d7#diff-2cebc83b629af08bd0b3a28229b2d903ec4ddfe4ea80d845612f2e5c8c38edc8R637

```
(4294967296, vec![0x1b,0x00,0x00,0x00,0x01,0x00,0x00,0x00,0x00]), // succeeds
(4294967295, vec![0x1b,0x00,0x00,0x00,0x00,0xff,0xff,0xff,0xff]) // fails
```

I encountered this while testing CBOR encoding of subcalls, I'm using a fixed size uint64 for the receiptId - however values which would fit into a u32 fail to be decoded by the oasis-cbor library.

https://github.com/oasisprotocol/sapphire-paratime/blob/CedarMist/delegate-staking-fixes/contracts/contracts/Subcall.sol#L478C25-L478C35

It's much simpler to use a fixed u64 (0x1b prefix) when CBOR encoding in Solidity, and I can't see anything in the [CBOR spec](https://www.rfc-editor.org/rfc/rfc8949.html) which says that this should fail.

**Comment by ptrus** [comment]
Probably due to the deterministic encoding rules: https://www.rfc-editor.org/rfc/rfc8949.html#name-core-deterministic-encoding

**Comment by CedarMist** [comment]
Ok that makes sense, I'll continue using my workaround to start receipt IDs at 4294967296.
